"""Add name column to modbus_data

Revision ID: af8f67e4b246
Revises: 
Create Date: 2023-09-28 11:41:35.410328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8f67e4b246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('modbus_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.drop_column('float_signed_value')

    with op.batch_alter_table('modbus_data16bit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modbus_data16bit', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('modbus_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('float_signed_value', sa.FLOAT(), nullable=True))
        batch_op.drop_column('name')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
